version: '3.5'
services:
  encoder_valiator:
    image: compuccino/encoder-validator:latest
    container_name: encoder-validator
    hostname: encoder-validator
    network_mode: host
    volumes:
      - ./validation-config:/validation-config
      - ./videos:/videos
      - ./app:/var/www/app
